// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: codepb/code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CodePb {

  /// <summary>Holder for reflection information generated from codepb/code.proto</summary>
  public static partial class CodeReflection {

    #region Descriptor
    /// <summary>File descriptor for codepb/code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjb2RlcGIvY29kZS5wcm90bxIGY29kZXBiKiAKBENvZGUSCwoHU3VjY2Vz",
            "cxAAEgsKB1Vua25vd24QAUIiWhdwcm90by1leGFtcGxlL2dvL2NvZGVwYqoC",
            "BkNvZGVQYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CodePb.Code), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Code {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Unknown")] Unknown = 1,
  }

  #endregion

}

#endregion Designer generated code
