// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgpb/msg.proto

package msgpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	codepb "proto-example/go/codepb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Good in cs, Bad in go
type EMessageCode int32

const (
	EMessageCode_CODE_Success EMessageCode = 0
	EMessageCode_CODE_UNKNOWN EMessageCode = 1
)

var EMessageCode_name = map[int32]string{
	0: "CODE_Success",
	1: "CODE_UNKNOWN",
}

var EMessageCode_value = map[string]int32{
	"CODE_Success": 0,
	"CODE_UNKNOWN": 1,
}

func (x EMessageCode) String() string {
	return proto.EnumName(EMessageCode_name, int32(x))
}

func (x EMessageCode) Number() int32 {
	return int32(x)
}

func (EMessageCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{0}
}

type ChangeType int32

const (
	ChangeType_UNKNOWN_CHANGE_TYPE ChangeType = 0
	ChangeType_CREATE              ChangeType = 1
	ChangeType_UPDATE              ChangeType = 2
	ChangeType_DELETE              ChangeType = 3
)

var ChangeType_name = map[int32]string{
	0: "UNKNOWN_CHANGE_TYPE",
	1: "CREATE",
	2: "UPDATE",
	3: "DELETE",
}

var ChangeType_value = map[string]int32{
	"UNKNOWN_CHANGE_TYPE": 0,
	"CREATE":              1,
	"UPDATE":              2,
	"DELETE":              3,
}

func (x ChangeType) String() string {
	return proto.EnumName(ChangeType_name, int32(x))
}

func (x ChangeType) Number() int32 {
	return int32(x)
}

func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{1}
}

type Code_Enum int32

const (
	Code_Success Code_Enum = 0
	Code_Unknown Code_Enum = 1
)

var Code_Enum_name = map[int32]string{
	0: "Success",
	1: "Unknown",
}

var Code_Enum_value = map[string]int32{
	"Success": 0,
	"Unknown": 1,
}

func (x Code_Enum) String() string {
	return proto.EnumName(Code_Enum_name, int32(x))
}

func (x Code_Enum) Number() int32 {
	return int32(x)
}

func (Code_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{1, 0}
}

type MsgId_Enum int32

const (
	MsgId_Unkown        MsgId_Enum = 0
	MsgId_LoginRequest  MsgId_Enum = 1
	MsgId_LoginResponse MsgId_Enum = 2
)

var MsgId_Enum_name = map[int32]string{
	0: "Unkown",
	1: "LoginRequest",
	2: "LoginResponse",
}

var MsgId_Enum_value = map[string]int32{
	"Unkown":        0,
	"LoginRequest":  1,
	"LoginResponse": 2,
}

func (x MsgId_Enum) String() string {
	return proto.EnumName(MsgId_Enum_name, int32(x))
}

func (x MsgId_Enum) Number() int32 {
	return int32(x)
}

func (MsgId_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{2, 0}
}

type MsgCode_Enum int32

const (
	MsgCode_Success MsgCode_Enum = 0
	MsgCode_Unknown MsgCode_Enum = 1
)

var MsgCode_Enum_name = map[int32]string{
	0: "Success",
	1: "Unknown",
}

var MsgCode_Enum_value = map[string]int32{
	"Success": 0,
	"Unknown": 1,
}

func (x MsgCode_Enum) String() string {
	return proto.EnumName(MsgCode_Enum_name, int32(x))
}

func (x MsgCode_Enum) Number() int32 {
	return int32(x)
}

func (MsgCode_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{3, 0}
}

type Msg_Id int32

const (
	Msg_IdUnkown        Msg_Id = 0
	Msg_IdLoginRequest  Msg_Id = 1
	Msg_IdLoginResponse Msg_Id = 2
)

var Msg_Id_name = map[int32]string{
	0: "IdUnkown",
	1: "IdLoginRequest",
	2: "IdLoginResponse",
}

var Msg_Id_value = map[string]int32{
	"IdUnkown":        0,
	"IdLoginRequest":  1,
	"IdLoginResponse": 2,
}

func (x Msg_Id) String() string {
	return proto.EnumName(Msg_Id_name, int32(x))
}

func (x Msg_Id) Number() int32 {
	return int32(x)
}

func (Msg_Id) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{4, 0}
}

type Msg_Code int32

const (
	Msg_CodeSuccess Msg_Code = 0
	Msg_CodeUnknown Msg_Code = 1
)

var Msg_Code_name = map[int32]string{
	0: "CodeSuccess",
	1: "CodeUnknown",
}

var Msg_Code_value = map[string]int32{
	"CodeSuccess": 0,
	"CodeUnknown": 1,
}

func (x Msg_Code) String() string {
	return proto.EnumName(Msg_Code_name, int32(x))
}

func (x Msg_Code) Number() int32 {
	return int32(x)
}

func (Msg_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{4, 1}
}

// A description of the historical or future-looking state of the
// resource pattern.
type ResourceDescriptor_History int32

const (
	// The "unset" value.
	ResourceDescriptor_HISTORY_UNSPECIFIED ResourceDescriptor_History = 0
	// The resource originally had one pattern and launched as such, and
	// additional patterns were added later.
	ResourceDescriptor_ORIGINALLY_SINGLE_PATTERN ResourceDescriptor_History = 1
	// The resource has one pattern, but the API owner expects to add more
	// later. (This is the inverse of ORIGINALLY_SINGLE_PATTERN, and prevents
	// that from being necessary once there are multiple patterns.)
	ResourceDescriptor_FUTURE_MULTI_PATTERN ResourceDescriptor_History = 2
)

var ResourceDescriptor_History_name = map[int32]string{
	0: "HISTORY_UNSPECIFIED",
	1: "ORIGINALLY_SINGLE_PATTERN",
	2: "FUTURE_MULTI_PATTERN",
}

var ResourceDescriptor_History_value = map[string]int32{
	"HISTORY_UNSPECIFIED":       0,
	"ORIGINALLY_SINGLE_PATTERN": 1,
	"FUTURE_MULTI_PATTERN":      2,
}

func (x ResourceDescriptor_History) String() string {
	return proto.EnumName(ResourceDescriptor_History_name, int32(x))
}

func (x ResourceDescriptor_History) Number() int32 {
	return int32(x)
}

func (ResourceDescriptor_History) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{5, 0}
}

// A flag representing a specific style that a resource claims to conform to.
type ResourceDescriptor_Style int32

const (
	// The unspecified value. Do not use.
	ResourceDescriptor_STYLE_UNSPECIFIED ResourceDescriptor_Style = 0
	// This resource is intended to be "declarative-friendly".
	//
	// Declarative-friendly resources must be more strictly consistent, and
	// setting this to true communicates to tools that this resource should
	// adhere to declarative-friendly expectations.
	//
	// Note: This is used by the API linter (linter.aip.dev) to enable
	// additional checks.
	ResourceDescriptor_DECLARATIVE_FRIENDLY ResourceDescriptor_Style = 1
)

var ResourceDescriptor_Style_name = map[int32]string{
	0: "STYLE_UNSPECIFIED",
	1: "DECLARATIVE_FRIENDLY",
}

var ResourceDescriptor_Style_value = map[string]int32{
	"STYLE_UNSPECIFIED":    0,
	"DECLARATIVE_FRIENDLY": 1,
}

func (x ResourceDescriptor_Style) String() string {
	return proto.EnumName(ResourceDescriptor_Style_name, int32(x))
}

func (x ResourceDescriptor_Style) Number() int32 {
	return int32(x)
}

func (ResourceDescriptor_Style) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{5, 1}
}

type Test struct {
	Code                 codepb.Code `protobuf:"varint,1,opt,name=code,proto3,enum=codepb.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetCode() codepb.Code {
	if m != nil {
		return m.Code
	}
	return codepb.Code_Success
}

type Code struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{1}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

type MsgId struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgId) Reset()         { *m = MsgId{} }
func (m *MsgId) String() string { return proto.CompactTextString(m) }
func (*MsgId) ProtoMessage()    {}
func (*MsgId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{2}
}

func (m *MsgId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgId.Unmarshal(m, b)
}
func (m *MsgId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgId.Marshal(b, m, deterministic)
}
func (m *MsgId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgId.Merge(m, src)
}
func (m *MsgId) XXX_Size() int {
	return xxx_messageInfo_MsgId.Size(m)
}
func (m *MsgId) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgId.DiscardUnknown(m)
}

var xxx_messageInfo_MsgId proto.InternalMessageInfo

type MsgCode struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCode) Reset()         { *m = MsgCode{} }
func (m *MsgCode) String() string { return proto.CompactTextString(m) }
func (*MsgCode) ProtoMessage()    {}
func (*MsgCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{3}
}

func (m *MsgCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCode.Unmarshal(m, b)
}
func (m *MsgCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCode.Marshal(b, m, deterministic)
}
func (m *MsgCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCode.Merge(m, src)
}
func (m *MsgCode) XXX_Size() int {
	return xxx_messageInfo_MsgCode.Size(m)
}
func (m *MsgCode) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCode.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCode proto.InternalMessageInfo

type Msg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{4}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

type ResourceDescriptor struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDescriptor) Reset()         { *m = ResourceDescriptor{} }
func (m *ResourceDescriptor) String() string { return proto.CompactTextString(m) }
func (*ResourceDescriptor) ProtoMessage()    {}
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5235907944b951b, []int{5}
}

func (m *ResourceDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDescriptor.Unmarshal(m, b)
}
func (m *ResourceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDescriptor.Marshal(b, m, deterministic)
}
func (m *ResourceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDescriptor.Merge(m, src)
}
func (m *ResourceDescriptor) XXX_Size() int {
	return xxx_messageInfo_ResourceDescriptor.Size(m)
}
func (m *ResourceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDescriptor proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("msgpb.EMessageCode", EMessageCode_name, EMessageCode_value)
	proto.RegisterEnum("msgpb.ChangeType", ChangeType_name, ChangeType_value)
	proto.RegisterEnum("msgpb.Code_Enum", Code_Enum_name, Code_Enum_value)
	proto.RegisterEnum("msgpb.MsgId_Enum", MsgId_Enum_name, MsgId_Enum_value)
	proto.RegisterEnum("msgpb.MsgCode_Enum", MsgCode_Enum_name, MsgCode_Enum_value)
	proto.RegisterEnum("msgpb.Msg_Id", Msg_Id_name, Msg_Id_value)
	proto.RegisterEnum("msgpb.Msg_Code", Msg_Code_name, Msg_Code_value)
	proto.RegisterEnum("msgpb.ResourceDescriptor_History", ResourceDescriptor_History_name, ResourceDescriptor_History_value)
	proto.RegisterEnum("msgpb.ResourceDescriptor_Style", ResourceDescriptor_Style_name, ResourceDescriptor_Style_value)
	proto.RegisterType((*Test)(nil), "msgpb.Test")
	proto.RegisterType((*Code)(nil), "msgpb.Code")
	proto.RegisterType((*MsgId)(nil), "msgpb.MsgId")
	proto.RegisterType((*MsgCode)(nil), "msgpb.MsgCode")
	proto.RegisterType((*Msg)(nil), "msgpb.Msg")
	proto.RegisterType((*ResourceDescriptor)(nil), "msgpb.ResourceDescriptor")
}

func init() { proto.RegisterFile("msgpb/msg.proto", fileDescriptor_d5235907944b951b) }

var fileDescriptor_d5235907944b951b = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x8f, 0xd2, 0x40,
	0x14, 0xc6, 0x29, 0xbb, 0x2c, 0xe6, 0x2d, 0x2e, 0xc3, 0xec, 0xaa, 0x68, 0x62, 0x42, 0x7a, 0xda,
	0xac, 0x11, 0x92, 0xf5, 0xa0, 0x89, 0x17, 0x6b, 0x3b, 0xc0, 0xc4, 0x52, 0xc8, 0x74, 0xaa, 0xa9,
	0x1e, 0x1a, 0x68, 0x27, 0x95, 0x2c, 0x74, 0x6a, 0xa7, 0x44, 0xf9, 0x97, 0xf4, 0x9f, 0x34, 0xd3,
	0xad, 0x90, 0xec, 0xc9, 0xd3, 0xbc, 0xf7, 0x7d, 0x2f, 0xf3, 0xcb, 0x97, 0xf7, 0xa0, 0xbb, 0x55,
	0x69, 0xbe, 0x1a, 0x6d, 0x55, 0x3a, 0xcc, 0x0b, 0x59, 0x4a, 0xdc, 0xaa, 0x84, 0x17, 0xbd, 0x58,
	0x26, 0x22, 0x5f, 0x8d, 0xf4, 0x73, 0xef, 0x98, 0xd7, 0x70, 0xca, 0x85, 0x2a, 0xf1, 0x00, 0x4e,
	0xb5, 0xda, 0x37, 0x06, 0xc6, 0xf5, 0xc5, 0x6d, 0x67, 0x78, 0x3f, 0x39, 0xb4, 0x65, 0x22, 0x58,
	0xe5, 0xe8, 0x49, 0xdd, 0x99, 0x03, 0x38, 0x25, 0xd9, 0x6e, 0x8b, 0xcf, 0xa1, 0xed, 0xef, 0xe2,
	0x58, 0x28, 0x85, 0x1a, 0xba, 0x09, 0xb2, 0xbb, 0x4c, 0xfe, 0xcc, 0x90, 0x61, 0x7e, 0x80, 0xd6,
	0x4c, 0xa5, 0x34, 0x31, 0xdf, 0xd6, 0xa3, 0x00, 0x67, 0x41, 0x76, 0xa7, 0xcd, 0x06, 0x46, 0xd0,
	0x71, 0x65, 0xba, 0xce, 0x98, 0xf8, 0xb1, 0x13, 0xaa, 0x44, 0x06, 0xee, 0xc1, 0xe3, 0x5a, 0x51,
	0xb9, 0xcc, 0x94, 0x40, 0x4d, 0xf3, 0x15, 0xb4, 0x67, 0x2a, 0xfd, 0x4f, 0xdc, 0x06, 0x4e, 0x66,
	0x2a, 0x35, 0xdf, 0x43, 0x93, 0x26, 0xb8, 0x03, 0x8f, 0x68, 0x72, 0x80, 0x61, 0xb8, 0xa0, 0xc9,
	0x03, 0xdc, 0x25, 0x74, 0x0f, 0xda, 0x01, 0x58, 0x87, 0xc3, 0x5d, 0x38, 0xd7, 0xef, 0x91, 0x54,
	0x0b, 0x47, 0xda, 0x1f, 0x03, 0x30, 0x13, 0x4a, 0xee, 0x8a, 0x58, 0x38, 0x42, 0xc5, 0xc5, 0x3a,
	0x2f, 0x65, 0x61, 0x7e, 0x83, 0xf6, 0x74, 0xad, 0x4a, 0x59, 0xec, 0xf1, 0x33, 0xb8, 0x9c, 0x52,
	0x9f, 0xcf, 0x59, 0x18, 0x05, 0x9e, 0xbf, 0x20, 0x36, 0x1d, 0x53, 0xe2, 0xa0, 0x06, 0x7e, 0x09,
	0xcf, 0xe7, 0x8c, 0x4e, 0xa8, 0x67, 0xb9, 0x6e, 0x18, 0xf9, 0xd4, 0x9b, 0xb8, 0x24, 0x5a, 0x58,
	0x9c, 0x13, 0xe6, 0x21, 0x03, 0xf7, 0xe1, 0x6a, 0x1c, 0xf0, 0x80, 0x91, 0x68, 0x16, 0xb8, 0x9c,
	0x1e, 0x9c, 0xa6, 0xf9, 0x0e, 0x5a, 0x7e, 0xb9, 0xdf, 0x08, 0xfc, 0x04, 0x7a, 0x3e, 0x0f, 0x5d,
	0xf2, 0xe0, 0xe3, 0x3e, 0x5c, 0x39, 0xc4, 0x76, 0x2d, 0x66, 0x71, 0xfa, 0x99, 0x44, 0x63, 0x46,
	0x89, 0xe7, 0xb8, 0x21, 0x32, 0x6e, 0x6e, 0xa1, 0x43, 0x66, 0x42, 0xa9, 0x65, 0x2a, 0xaa, 0x7c,
	0x08, 0x3a, 0xf6, 0xdc, 0x21, 0xd1, 0x31, 0xe0, 0x3f, 0x25, 0xf0, 0x3e, 0x79, 0xf3, 0x2f, 0x1e,
	0x32, 0x6e, 0x28, 0x80, 0xfd, 0x7d, 0x99, 0xa5, 0x82, 0xef, 0x73, 0xa1, 0xd3, 0xd4, 0x56, 0x64,
	0x4f, 0x2d, 0x6f, 0x42, 0x22, 0x1e, 0x2e, 0x08, 0x6a, 0xe8, 0xa5, 0xda, 0x8c, 0x58, 0x9c, 0x20,
	0xa3, 0x5a, 0xf0, 0xc2, 0xd1, 0x75, 0x53, 0xd7, 0x0e, 0x71, 0x09, 0x27, 0xe8, 0xe4, 0xe3, 0xe0,
	0xeb, 0xd3, 0xea, 0xcc, 0x5e, 0x8b, 0x5f, 0xcb, 0x6d, 0xbe, 0x11, 0xa3, 0x54, 0x8e, 0xaa, 0x53,
	0xfc, 0xdd, 0xd4, 0x27, 0xb2, 0x58, 0xad, 0xce, 0x2a, 0xff, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf3, 0xa5, 0xeb, 0x1f, 0xb3, 0x02, 0x00, 0x00,
}
